# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ksusha\PycharmProjects\Графика\albertiWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlbertiWindow(object):
    def setupUi(self, AlbertiWindow):
        AlbertiWindow.setObjectName("AlbertiWindow")
        AlbertiWindow.resize(900, 900)
        AlbertiWindow.setMinimumSize(QtCore.QSize(900, 900))
        AlbertiWindow.setMaximumSize(QtCore.QSize(900, 900))
        self.centralwidget = QtWidgets.QWidget(AlbertiWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout.addWidget(self.plainTextEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout.addWidget(self.plainTextEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        AlbertiWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AlbertiWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 18))
        self.menubar.setObjectName("menubar")
        AlbertiWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AlbertiWindow)
        self.statusbar.setObjectName("statusbar")
        AlbertiWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AlbertiWindow)
        QtCore.QMetaObject.connectSlotsByName(AlbertiWindow)

    def retranslateUi(self, AlbertiWindow):
        _translate = QtCore.QCoreApplication.translate
        AlbertiWindow.setWindowTitle(_translate("AlbertiWindow", "КМЗИ"))
        self.label.setText(_translate("AlbertiWindow", "Введите текст:"))
        self.label_2.setText(_translate("AlbertiWindow", "Введите ключ для алфавита:"))
        self.label_3.setText(_translate("AlbertiWindow", "Введите ключ для зашифрования:"))
        self.pushButton.setText(_translate("AlbertiWindow", "ЗАШИФРОВАТЬ"))
        self.pushButton_2.setText(_translate("AlbertiWindow", "РАСШИФРОВАТЬ"))
        self.pushButton_3.setText(_translate("AlbertiWindow", "Очистить"))
