# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ksusha\PycharmProjects\Графика\adbashWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdbashWindow(object):
    def setupUi(self, AdbashWindow):
        AdbashWindow.setObjectName("AdbashWindow")
        AdbashWindow.resize(900, 900)
        AdbashWindow.setMinimumSize(QtCore.QSize(900, 900))
        AdbashWindow.setMaximumSize(QtCore.QSize(900, 900))
        self.centralwidget = QtWidgets.QWidget(AdbashWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout.addWidget(self.plainTextEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout.addWidget(self.plainTextEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        AdbashWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AdbashWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 18))
        self.menubar.setObjectName("menubar")
        AdbashWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AdbashWindow)
        self.statusbar.setObjectName("statusbar")
        AdbashWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AdbashWindow)
        QtCore.QMetaObject.connectSlotsByName(AdbashWindow)

    def retranslateUi(self, AdbashWindow):
        _translate = QtCore.QCoreApplication.translate
        AdbashWindow.setWindowTitle(_translate("AdbashWindow", "КМЗИ"))
        self.label.setText(_translate("AdbashWindow", "Введите текст:"))
        self.pushButton.setText(_translate("AdbashWindow", "ЗАШИФРОВАТЬ"))
        self.pushButton_2.setText(_translate("AdbashWindow", "РАСШИФРОВАТЬ"))
        self.pushButton_3.setText(_translate("AdbashWindow", "Очистить"))
