# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ksusha\PycharmProjects\Графика\cardanoWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CardanoWindow(object):
    def setupUi(self, CardanoWindow):
        CardanoWindow.setObjectName("CardanoWindow")
        CardanoWindow.resize(900, 900)
        CardanoWindow.setMinimumSize(QtCore.QSize(900, 900))
        CardanoWindow.setMaximumSize(QtCore.QSize(900, 900))
        self.centralwidget = QtWidgets.QWidget(CardanoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        #self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout.addWidget(self.plainTextEdit_3)
        #self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        #self.pushButton_2.setObjectName("pushButton_2")
        #self.verticalLayout.addWidget(self.pushButton_2)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout.addWidget(self.plainTextEdit_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        CardanoWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CardanoWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 708, 18))
        self.menubar.setObjectName("menubar")
        CardanoWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CardanoWindow)
        self.statusbar.setObjectName("statusbar")
        CardanoWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CardanoWindow)
        QtCore.QMetaObject.connectSlotsByName(CardanoWindow)

    def retranslateUi(self, CardanoWindow):
        _translate = QtCore.QCoreApplication.translate
        CardanoWindow.setWindowTitle(_translate("CardanoWindow", "MainWindow"))
        self.label.setText(_translate("CardanoWindow", "Введите текст:"))
        self.label_3.setText(_translate("CardanoWindow", "Длина вводимого текста:"))
        self.label_2.setText(_translate("CardanoWindow", "Введите размер:"))
        self.pushButton.setText(_translate("CardanoWindow", "ЗАШИФРОВАТЬ И РАСШИФРОВАТЬ"))
        #self.pushButton_2.setText(_translate("CardanoWindow", "РАСШИФРОВАТЬ"))
        self.pushButton_3.setText(_translate("CardanoWindow", "Очистить"))
        self.pushButton_4.setText(_translate("CardanoWindow", "Показать решётку Кардано"))
