# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ksusha\PycharmProjects\Графика\cazarWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CaezarWindow(object):
    def setupUi(self, CaezarWindow):
        CaezarWindow.setObjectName("CaezarWindow")
        CaezarWindow.resize(469, 320)
        CaezarWindow.setMinimumSize(QtCore.QSize(469, 320))
        CaezarWindow.setMaximumSize(QtCore.QSize(469, 320))
        self.centralwidget = QtWidgets.QWidget(CaezarWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 30, 411, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 160, 411, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 220, 411, 20))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 110, 101, 17))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 190, 101, 17))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 250, 56, 17))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 0, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 391, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(30, 80, 411, 22))
        self.spinBox.setMaximum(99)
        self.spinBox.setProperty("value", 0)
        self.spinBox.setObjectName("spinBox")
        CaezarWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CaezarWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 469, 18))
        self.menubar.setObjectName("menubar")
        CaezarWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CaezarWindow)
        self.statusbar.setObjectName("statusbar")
        CaezarWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CaezarWindow)
        QtCore.QMetaObject.connectSlotsByName(CaezarWindow)

    def retranslateUi(self, CaezarWindow):
        _translate = QtCore.QCoreApplication.translate
        CaezarWindow.setWindowTitle(_translate("CaezarWindow", "MainWindow"))
        self.pushButton.setText(_translate("CaezarWindow", "ЗАШИФРОВАТЬ"))
        self.pushButton_2.setText(_translate("CaezarWindow", "РАСШИФРОВАТЬ"))
        self.pushButton_3.setText(_translate("CaezarWindow", "Очистить"))
        self.label.setText(_translate("CaezarWindow", "Введите текст:"))
        self.label_2.setText(_translate("CaezarWindow", "Введите сдвиг:"))
        self.label_4.setText(_translate("CaezarWindow", "Введите текст:"))
