# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ksusha\PycharmProjects\Графика\chastotaWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChastWindow(object):
    def setupUi(self, ChastWindow):
        ChastWindow.setObjectName("ChastWindow")
        ChastWindow.resize(1513, 729)
        self.centralwidget = QtWidgets.QWidget(ChastWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 5, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 5, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 6, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 1, 0, 1, 4)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout.addWidget(self.plainTextEdit_2, 4, 0, 1, 4)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 2, 2, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 9, 2, 1, 1)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout.addWidget(self.plainTextEdit_3, 1, 5, 8, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 3, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 8, 2, 1, 1)
        ChastWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChastWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1513, 18))
        self.menubar.setObjectName("menubar")
        ChastWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChastWindow)
        self.statusbar.setObjectName("statusbar")
        ChastWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChastWindow)
        QtCore.QMetaObject.connectSlotsByName(ChastWindow)

    def retranslateUi(self, ChastWindow):
        _translate = QtCore.QCoreApplication.translate
        ChastWindow.setWindowTitle(_translate("ChastWindow", "MainWindow"))
        self.pushButton.setText(_translate("ChastWindow", "Очистить"))
        self.label.setText(_translate("ChastWindow", "Введите текст:"))
        self.label_4.setText(_translate("ChastWindow", "Таблица вероятных символов:"))
        self.pushButton_2.setText(_translate("ChastWindow", "Выгрузить в файл"))
        self.pushButton_4.setText(_translate("ChastWindow", "Загрузить из файла"))
        self.pushButton_3.setText(_translate("ChastWindow", "Расшифровать"))
        self.pushButton_5.setText(_translate("ChastWindow", "Показать гистограмму частот"))
        self.label_2.setText(_translate("ChastWindow", "Заменить"))
        self.pushButton_6.setText(_translate("ChastWindow", "Заменить"))
        self.label_3.setText(_translate("ChastWindow", "на"))
