# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ksusha\PycharmProjects\Графика\playfairWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlayfairWindow(object):
    def setupUi(self, PlayfairWindow):
        PlayfairWindow.setObjectName("PlayfairWindow")
        PlayfairWindow.resize(900, 900)
        PlayfairWindow.setMinimumSize(QtCore.QSize(900, 900))
        PlayfairWindow.setMaximumSize(QtCore.QSize(900, 900))
        self.centralwidget = QtWidgets.QWidget(PlayfairWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout.addWidget(self.plainTextEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout.addWidget(self.plainTextEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        # self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton_4.setObjectName("pushButton_4")
        # self.verticalLayout.addWidget(self.pushButton_4)
        # self.label_3 = QtWidgets.QLabel(self.centralwidget)
        # self.label_3.setObjectName("label_3")
        # self.verticalLayout.addWidget(self.label_3)
        PlayfairWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PlayfairWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 18))
        self.menubar.setObjectName("menubar")
        PlayfairWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PlayfairWindow)
        self.statusbar.setObjectName("statusbar")
        PlayfairWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlayfairWindow)
        QtCore.QMetaObject.connectSlotsByName(PlayfairWindow)

    def retranslateUi(self, PlayfairWindow):
        _translate = QtCore.QCoreApplication.translate
        PlayfairWindow.setWindowTitle(_translate("PlayfairWindow", "MainWindow"))
        self.label.setText(_translate("PlayfairWindow", "Введите текст:"))
        self.label_2.setText(_translate("PlayfairWindow", "Введите ключ для алфавита:"))
        self.pushButton.setText(_translate("PlayfairWindow", "ЗАШИФРОВАТЬ"))
        self.pushButton_2.setText(_translate("PlayfairWindow", "РАСШИФРОВАТЬ"))
        self.pushButton_3.setText(_translate("PlayfairWindow", "Очистить"))
        # self.pushButton_4.setText(_translate("PlayfairWindow", "Показать таблицу"))
        # self.label_3.setText(_translate("PlayfairWindow", ""))
