# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ksusha\PycharmProjects\Графика\adbashWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PolybiusWindow(object):
    def setupUi(self, PolybiusWindow):
        PolybiusWindow.setObjectName("AdbashWindow")
        PolybiusWindow.resize(900, 900)
        PolybiusWindow.setMinimumSize(QtCore.QSize(900, 900))
        PolybiusWindow.setMaximumSize(QtCore.QSize(900, 900))
        self.centralwidget = QtWidgets.QWidget(PolybiusWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout.addWidget(self.plainTextEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout.addWidget(self.plainTextEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        PolybiusWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PolybiusWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 18))
        self.menubar.setObjectName("menubar")
        PolybiusWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PolybiusWindow)
        self.statusbar.setObjectName("statusbar")
        PolybiusWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PolybiusWindow)
        QtCore.QMetaObject.connectSlotsByName(PolybiusWindow)

    def retranslateUi(self, PolybiusWindow):
        _translate = QtCore.QCoreApplication.translate
        PolybiusWindow.setWindowTitle(_translate("PolybiusWindow", "КМЗИ"))
        self.label.setText(_translate("PolybiusWindow", "Введите текст:"))
        self.pushButton.setText(_translate("PolybiusWindow", "ЗАШИФРОВАТЬ"))
        self.pushButton_2.setText(_translate("PolybiusWindow", "РАСШИФРОВАТЬ"))
        self.pushButton_3.setText(_translate("PolybiusWindow", "Очистить"))
