# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ksusha\PycharmProjects\Графика\richelieuWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RichelieuWindow(object):
    def setupUi(self, RichelieuWindow):
        RichelieuWindow.setObjectName("RichelieuWindow")
        RichelieuWindow.resize(900, 900)
        RichelieuWindow.setMinimumSize(QtCore.QSize(900, 900))
        RichelieuWindow.setMaximumSize(QtCore.QSize(900, 900))
        self.centralwidget = QtWidgets.QWidget(RichelieuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        #self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout.addWidget(self.plainTextEdit_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout.addWidget(self.plainTextEdit_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        RichelieuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RichelieuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 18))
        self.menubar.setObjectName("menubar")
        RichelieuWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RichelieuWindow)
        self.statusbar.setObjectName("statusbar")
        RichelieuWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RichelieuWindow)
        QtCore.QMetaObject.connectSlotsByName(RichelieuWindow)

    def retranslateUi(self, RichelieuWindow):
        _translate = QtCore.QCoreApplication.translate
        RichelieuWindow.setWindowTitle(_translate("RichelieuWindow", "MainWindow"))
        self.label.setText(_translate("RichelieuWindow", "Введите текст:"))
        self.label_2.setText(_translate("RichelieuWindow", "Введите ключ:"))
        self.pushButton.setText(_translate("RichelieuWindow", "ЗАШИФРОВАТЬ"))
        self.pushButton_2.setText(_translate("RichelieuWindow", "РАСШИФРОВАТЬ"))
        self.pushButton_3.setText(_translate("RichelieuWindow", "Очистить"))
