# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ksusha\PycharmProjects\Графика\skitalaWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SkitalaWindow(object):
    def setupUi(self, SkitalaWindow):
        SkitalaWindow.setObjectName("SkitalaWindow")
        SkitalaWindow.resize(900, 900)
        SkitalaWindow.setMinimumSize(QtCore.QSize(900, 900))
        SkitalaWindow.setMaximumSize(QtCore.QSize(900, 900))
        self.centralwidget = QtWidgets.QWidget(SkitalaWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout.addWidget(self.plainTextEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout.addWidget(self.plainTextEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        SkitalaWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SkitalaWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 900))
        self.menubar.setObjectName("menubar")
        SkitalaWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SkitalaWindow)
        self.statusbar.setObjectName("statusbar")
        SkitalaWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SkitalaWindow)
        QtCore.QMetaObject.connectSlotsByName(SkitalaWindow)

    def retranslateUi(self, SkitalaWindow):
        _translate = QtCore.QCoreApplication.translate
        SkitalaWindow.setWindowTitle(_translate("SkitalaWindow", "КМЗИ"))
        self.label.setText(_translate("SkitalaWindow", "Введите текст:"))
        self.label_2.setText(_translate("SkitalaWindow", "Введите количество строк:"))
        self.pushButton.setText(_translate("SkitalaWindow", "ЗАШИФРОВАТЬ"))
        self.pushButton_2.setText(_translate("SkitalaWindow", "РАСШИФРОВАТЬ"))
        self.pushButton_3.setText(_translate("SkitalaWindow", "Очистить"))
